version: "3.3"
services:
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgSTRONGpass
    ports:
      - 5444:5432
    restart: unless-stopped

  omnidb:
    build: ./.omnidb
    ports:
      - 8010:8000
    restart: unless-stopped
